apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-03-29T07:18:01Z"
    generation: 2
    labels:
      app: java-app-kube
    name: java-app-kube
    namespace: default
    resourceVersion: "12958"
    uid: ec4a469d-c1ca-4a0a-90e1-f8d006dc36b6
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: java-app-kube
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: java-app-kube
      spec:
        containers:
        - image: prashanth7993/java-app:v3
          imagePullPolicy: IfNotPresent
          name: java-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-03-29T07:18:03Z"
      lastUpdateTime: "2025-03-29T07:18:03Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-03-29T07:18:01Z"
      lastUpdateTime: "2025-03-29T07:18:03Z"
      message: ReplicaSet "java-app-kube-774fb769b9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
